Allow toggle for 5xx response content from endpoints #patch
kiwigrid/k8s-sidecar pull request #127
Opened 2021-05-21 16:13 UTC by raghavtan

Currently the sidecar doesn't create file (from endpoints giving 5xx response) on the volume mounted on the pod 
The `bool` environment variable `ENABLE_5XX` will enable an option/toggle to save/write content from 5xx upstream/endpoint responses

#patch

2021-05-25 11:00 UTC, jekkel requested changes
Thanks for your contribution! PR looks good already, some minor things left.

2021-05-25 11:25 UTC, raghavtan commented on README.md
> +  - description: Set to true to enable pulling of 5XX response content from config map
@jekkel Updated readme documentation to reference `*.url` feature for `ENABLE_5XX` env var

2021-05-25 11:26 UTC, raghavtan commented on sidecar/sidecar.py
> +                           current_namespace, folder_annotation, res, unique_filenames, script, enable_5xx)
@jekkel refactored the order of args for method `list_resources` definition

2021-05-25 11:27 UTC, raghavtan commented on sidecar/helpers.py
> +                    status_forcelist=list() if enable_5xx else [500, 502, 503, 504])
added new variable `enforce_status_codes` to replace inline expression

2021-05-25 14:52 UTC, jekkel reviewed
All changes look good so far. Can imagine adding a test to circleCI test script verifying the url feature works as intended with and without 500 responses? Ideally this should not do any requests to the outside world, we probably should install a small static webserver to the kind k8s cluster serving some files...? WDYT?

2021-05-25 16:34 UTC, raghavtan commented
> All changes look good so far. Can you imagine adding a test to circleCI test script verifying the url feature works as intended with and without 500 responses? Ideally this should not do any requests to the outside world, we probably should install a small static webserver to the kind k8s cluster serving some files...? WDYT?

This wound aptly be 2x all the tests with and without `ENABLE_5XX` flag
- 2 separate sidecar pods with different flags 
- a dummy http server pod serving custom content html pages which can be compared with `verify_resources_read` 

Adding a sample test scenario with multiple sidecar containers and validation to `verify_resources_read`  (not adding the dummy static server for now)

@jekkel how would this setup be in your opinion ?

2021-05-25 18:30 UTC, jekkel commented
Yes, that's exactly the kind of setup I was thinking about. Would you be able to integrate that into this PR?

2021-05-25 22:17 UTC, raghavtan commented
> Yes, that's exactly the kind of setup I was thinking about. Would you be able to integrate that into this PR?

Added @jekkel 
- test scenario script updated
- deployment for dummy server image
- added dummy server

2021-05-26 06:09 UTC, jekkel approved these changes

2021-05-26 06:10 UTC, merged

2021-05-26 07:30 UTC, jekkel commented
We need to fix a CI issue but the feature is going to be in the next version. Thanks for your contribution again!

2021-05-26 09:27 UTC, raghavtan commented
> We need to fix a CI issue but the feature is going to be in the next version. Thanks for your contribution again!

@jekkel not to pester, but when can we expect the CI to be fixed and the feature released. Need the feature to implement it on our edge-stack

2021-05-26 09:31 UTC, jekkel commented
It's a matter of hours or days at most, sorry for any inconvenience.

2021-05-26 09:35 UTC, raghavtan commented
No worries at all, lemme know if i can be any help in the process

2021-05-29 07:05 UTC, jekkel commented
Ping @manu11th

2021-06-16 09:31 UTC, jekkel commented
@raghavtan FYI released [v1.12.1](https://github.com/kiwigrid/k8s-sidecar/releases/tag/1.12.1)