Update helpers.py
kiwigrid/k8s-sidecar pull request #135
Opened 2021-06-27 19:27 UTC by haf

Fixes #76 

Docs https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html — basically, having 0.25 eats the five retries way too quickly, especially when it comes to connecting the socket over a network that might take a few seconds to establish the TCP connection.

Relevant docs:

> A backoff factor to apply between attempts after the second try (most errors are resolved immediately by a second try without a delay). urllib3 will sleep for:
> `{backoff factor} * (2 ** ({number of total retries} - 1))`
> seconds. If the backoff_factor is 0.1, then sleep() will sleep for [0.0s, 0.2s, 0.4s, …] between retries. It will never be longer than Retry.BACKOFF_MAX.
> By default, backoff is disabled (set to 0).

2021-06-28 09:02 UTC, jekkel requested changes
Please adjust README.md with the changed defaults, looks good otherwise.

2021-06-28 14:48 UTC, haf commented
Feel free to make the changes you need to merge this. I’m on vacation and will not get back to this PR.

2021-06-29 08:20 UTC, jekkel commented
Nu hurry, since all the values are already configurable this change can wait a bit.

2021-09-07 06:57 UTC, jekkel approved these changes

2021-09-07 06:58 UTC, merged