Support for comma separated namespaces
kiwigrid/k8s-sidecar pull request #136
Opened 2021-07-07 14:43 UTC by Allex1

Addresses https://github.com/kiwigrid/k8s-sidecar/issues/9

@pulledtim @jekkel @raghavtan  please review

2021-07-07 18:23 UTC, jekkel requested changes
The overall approach looks good to me. But could you please unify namespace handling? Right now it's confusing where the environment variable is being evaluated and it happens in multiple places. I suggest to determine the required namespace at the very start of the sidecar.

Beside that we're dealing with 2 situations:
1. `ALL`
2. a list of specific namespaces

How about adding some object orientation to this such that there are 2 sub classes of an abstract `NamespaceConfig` class representing the 2 case. The sub classes can also provide the methods to use the k8s client for the 2 different cases so that the code making use of them doesn't have to deal with the distinction. Anyway - object oriented or not - the handling of namespaces should be simplified with the addition of the multi-namespace feature.

Last but not least please add an appropriate test case verifying the feature works as intended for all tested k8s versions.

2021-07-07 18:23 UTC, jekkel commented on sidecar/resources.py
> +    if current_namespace == "ALL":
I don't think `current_namespace` can be `ALL` at this point since it is not a user provided argument but the auto detected *current* namespace.

2021-07-12 18:45 UTC, serban21 commented
@jekkel I'm helping @Allex1 with this issue. Thanks for the comment.

On namespace handling. 

I agree that the namespace should be read at the start, I'll change that.

The 2 situation description is partially correct. Yes, viewed from outside it is so. However in the code I split the namespace list before starting watcher processes, so each namespace will have a process for each resource type. This is needed for processing `Watch` stream, since as far as I can tell a process is needed for each stream. Thus after starting the processes, we have the following namespace situation:

1. `ALL`
2. A single namespace

So I don't think we need to do this kind of refactor. I'll do some other changes that could improve readability. One major thing would be to see if `_watch_resource_iterator` and `list_resources` can be unified, perhaps with a similar class structure? But I'm afraid to do this now, perhaps I'll add it as a separate issue and address it afterwards.

Btw, I just realised that there is a bug on using `METHOD` `LIST`, since that is not going to start multiple processes. Fixing should be easy.

Regrading the tests, I looked at them, but I'm having problems in running them locally or on a fork CircleCI, I'm getting the same error on both: ```Must provide --username with --password-stdin```, on line ```echo "${DOCKER_PASSWORD}" | docker login --username="${DOCKER_USERNAME}" --password-stdin docker.io```. Can you tell me how to fix this, or can I get permission to push a branch into the repo, to run the tests into you CircleCI setup?

2021-07-14 09:20 UTC, Allex1 commented
@jekkel can you have another look pls ?

2021-08-17 10:11 UTC, Allex1 commented
@jekkel ?

2021-09-06 08:06 UTC, jekkel reviewed
Your changes look very good, thanks for your effort! If you're not able to run the tests on your own I can do it within the org with a temporay branch...

2021-09-06 08:06 UTC, jekkel commented
@serban21 you can fix that by providing the secrets `DOCKER_USERNAME` and `DOCKER_PASSWORD` within your circleCI configuration, those will be available in the pipeline as environment variables then.

> Btw, I just realised that there is a bug on using METHOD LIST, since that is not going to start multiple processes. Fixing should be easy.

Great catch! :+1:

2021-09-06 08:11 UTC, jekkel approved these changes

2021-09-06 08:12 UTC, merged