Add multi-arch builds with docker buildx
kiwigrid/k8s-sidecar pull request #86
Opened 2020-08-18 22:54 UTC by cablespaghetti

Uses docker buildx to build images to arm/v7 and arm64 as well as amd64. Also updated Kubernetes versions used and the build container version.

Working pipeline (before I changed the Docker Hub image name back to yours) here: https://app.circleci.com/pipelines/github/cablespaghetti/k8s-sidecar
Resulting images here: https://hub.docker.com/r/cablespaghetti/k8s-sidecar

I have had to rebuild on the deploy step as I'm not sure of a way to pull and re-push the whole manifest list.
I've also not tested with docker_layer_caching enabled as this isn't on the free plan of Circle CI. But I don't imagine this makes a big difference.

Closes #48

2020-08-19 13:57 UTC, cablespaghetti commented
Here's the latest build: https://app.circleci.com/pipelines/github/cablespaghetti/k8s-sidecar/32/workflows/8b80b8bf-4b00-41d5-a8e2-8eb2d2f51d33

Found a workaround for having to rebuild the containers to deploy.

2020-08-19 13:58 UTC, cablespaghetti commented
@monotek I think this is ready for review now :)

2020-08-19 15:36 UTC, monotek requested changes
Please keep k8s versions 1.14 & 1.15 for now

2020-08-19 15:43 UTC, monotek approved these changes

2020-08-19 15:44 UTC, monotek requested changes
Please fix ci

2020-08-19 15:55 UTC, cablespaghetti commented
I've got my `master` branch passing again now with the extra versions. I can't get this branch to pass because I can't enable docker_layer_caching on my free circle ci account and don't have permissions to push to `kiwigrid/k8s-sidecar` on docker hub.

Here is the diff between this branch and the working branch:
```
diff --git a/.circleci/config.yml b/.circleci/config.yml
index e8b5134..6a41db1 100644
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -39,7 +39,7 @@ jobs:
 
       - setup_remote_docker:
           version: 19.03.12
-          docker_layer_caching: true
+      #    docker_layer_caching: true
 
       - run: |
           TAG=0.1.$CIRCLE_BUILD_NUM
@@ -52,7 +52,7 @@ jobs:
           docker context create buildcontext
           docker buildx create buildcontext --use
           docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
-          docker buildx build --push -t kiwigrid/k8s-sidecar-build:$TAG --platform linux/amd64,linux/arm64,linux/arm/v7 .
+          docker buildx build --push -t cablespaghetti/k8s-sidecar-build:$TAG --platform linux/amd64,linux/arm64,linux/arm/v7 .
 
       - persist_to_workspace:
           root: /tmp
@@ -158,7 +158,7 @@ jobs:
       - checkout
       - setup_remote_docker:
           version: 19.03.12
-          docker_layer_caching: true
+      #    docker_layer_caching: true
 
       - run: |
           TAG=`cat /tmp/VERSION`
@@ -170,7 +170,7 @@ jobs:
           docker context create buildcontext
           docker buildx create buildcontext --use
           docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
-          echo "FROM kiwigrid/k8s-sidecar-build:$TAG" | docker buildx build --push -t kiwigrid/k8s-sidecar:$TAG -t kiwigrid/k8s-sidecar:latest --platform linux/amd64,linux/arm64,linux/arm/v7 -
+          echo "FROM cablespaghetti/k8s-sidecar-build:$TAG" | docker buildx build --push -t cablespaghetti/k8s-sidecar:$TAG -t cablespaghetti/k8s-sidecar:latest --platform linux/amd64,linux/arm64,linux/arm/v7 -
 
 workflows:
   version: 2
diff --git a/.circleci/test/sidecar.yaml b/.circleci/test/sidecar.yaml
index 77debf1..14a48e6 100644
--- a/.circleci/test/sidecar.yaml
+++ b/.circleci/test/sidecar.yaml
@@ -34,7 +34,7 @@ spec:
   serviceAccountName: sample-acc
   containers:
   - name: sidecar
-    image: kiwigrid/k8s-sidecar-build:SIDECAR_VERSION
+    image: cablespaghetti/k8s-sidecar-build:SIDECAR_VERSION
     volumeMounts:
     - name: shared-volume
```

Please see the latest build here:
https://app.circleci.com/pipelines/github/cablespaghetti/k8s-sidecar

Thanks!

2020-08-28 13:36 UTC, crlane commented
Any update on this? would love to see https://github.com/helm/charts/issues/23405 move forward.

2020-08-28 14:27 UTC, cablespaghetti commented
Found a workaround for the different Docker repo names and have just remove docker layer caching so it'll run on my Circle CI free account.

2020-08-28 20:33 UTC, merged

2020-08-29 14:01 UTC, cablespaghetti commented
@monotek Thanks so much for merging this! It looks like the build has failed after merging for no good reason (the 1.15 test got stuck). Any chance you could retry the build?

2020-08-30 07:01 UTC, monotek commented
Still fails: https://app.circleci.com/pipelines/github/kiwigrid/k8s-sidecar/39/workflows/1083bae4-b3f6-4e15-8607-a50dc2737086/jobs/200

2020-08-30 08:15 UTC, cablespaghetti commented
That's really annoying! It worked fine before merging. :(

Seems to be this issue: https://github.com/docker/buildx/issues/235

I'll see if there is a better fix, but I'd just re-run the whole pipeline for now. Sorry about this...

2020-09-01 12:49 UTC, monotek commented
It worked now :)

https://app.circleci.com/jobs/github/kiwigrid/k8s-sidecar/201